# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('resources/*', 'resources'),
    ],
    hiddenimports=[
        'autotune',
        'autotune.msp',
        'autotune.msp.commands',
        'autotune.msp.protocol',
        'autotune.msp.transport',
        'autotune.fc',
        'autotune.fc.pid',
        'autotune.fc.rate',
        'autotune.fc.config',
        'autotune.fc.controller',
        'autotune.acquisition',
        'autotune.acquisition.telemetry',
        'autotune.acquisition.blackbox',
        'autotune.acquisition.recorder',
        'autotune.analysis',
        'autotune.analysis.signal_processing',
        'autotune.analysis.step_response',
        'autotune.analysis.metrics',
        'autotune.tuning',
        'autotune.tuning.pid_tuner',
        'autotune.tuning.rate_tuner',
        'autotune.tuning.rules',
        'autotune.tuning.optimizer',
        'autotune.ui',
        'autotune.ui.main_window',
        'autotune.ui.connection_panel',
        'autotune.ui.pid_panel',
        'autotune.ui.rate_panel',
        'autotune.ui.chart_panel',
        'autotune.ui.tuning_wizard',
        'autotune.ui.profile_panel',
        'autotune.ui.styles',
        'autotune.utils',
        'autotune.utils.logger',
        'autotune.utils.profile_manager',
        'serial.tools.list_ports',
        'pyqtgraph',
        'numpy',
        'scipy',
        'scipy.signal',
        'scipy.fft',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='AutoTune',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='AutoTune',
)